{
package main

func main() {
	in := os.Stdin
	if len(os.Args) > 1 {
		f, err := os.Open(os.Args[1])
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close()
		in = f
	}
	got, err := ParseReader("", in, Debug(true))
	fmt.Println(got, err)
}


}

start = #{fmt.Println("start");state["countCs"] = 0;return nil} ((x/y) ws*)* { fmt.Println(state["countCs"]); return state["countCs"],nil }

x = "ab" c "d"
y = "a" bc "e"

c = "c" #{ fmt.Println("c");state["countCs"] = state["countCs"].(int)+3; return nil }
bc = "bc" #{ fmt.Println("bc");state["countCs"] = state["countCs"].(int)+1; return nil}

ws = " " / "\n"
